_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 55
            "4": 3.9.21
            "5": 0.20.1
            "12": 0.20.1
            "13": darwin-arm64
